### ISSUE TITLE
Input error

### ISSUE THREAD

**Issue by vattyboy** [RomanFenioux/Skin_Lesion#1]
Gave input imge id as 002. but got an invalid error message. I'm new to MATLAB, so just trying to understand.

**Comment by RomanFenioux** [comment]
I can't reproduce the error
- can you copy the exact message ?
- in OneImageSegt.m is the path set to '../data/norestriction' ? 
- does the file 'ISIC_0000002.jpg' exist in data/norestriction/training/melanoma/ ? 
- does the file 'ISIC_0000002_segmentation.png' exist in data/norestriction/truth/melanoma/ ? 
- the input you give is 002 (no quote mark, etc) ?
- does the error happen before you get the method input ? (choosing between otsu, srm, levelset) ?

**Comment by vattyboy** [comment]
Thank you so much for replying back.
It is not not exactly an error, but warnings and a blank output. I tried it
on versions R2014b & R2017a, even tried waiting for some time, thinking
that my system might be slow.ut the output remains blank.
I made absolutely no changes to your code or the folders in which the data
was stored. I'm sending along two screenshots.
Thank you.

**Comment by RomanFenioux** [comment]
My version is R2015b, and the program also uses the image toolbox so make sure you have it installed.
Which one of the methods are you testing ? I recommend otsu first, as it is fully automated.
I'm waiting for the screenshots.

**Comment by vattyboy** [comment]
So, i opened the OTSU MATLAB file, and added   I= imread('imagename'), then
the output was shown below.
Is that what you recommended? Is that the desired output? if yes, then what
do i do next, like which file to run next to try and understand this?
Or did you mean i had to open the segEvaluation.m file and choose otsu as
the required method, coz then the output is NaN, along with warnings and
blank graphs.

**Comment by RomanFenioux** [comment]
ok I did not get the images and I think this is because you attach them to the email reply. Try to answer on the github thread and to insert the images from here. 

Until then I will try my best to make sure you have used the program correctly (I know I was lazy when writing the README).
What I meant by "test otsu first" is  :
- open "OneImageSegt.m" and launch it 
- the console will ask you for inputs and you enter the following (your input is in bold):
>> image id (3 digits) : **002 + [enter]**
>> segmentation method (otsu, srm, region, levelset): **otsu + [enter]**
- then a figure should appear with the image of the lesion displayed, a red line representing the segmentation obtained with otsu and a green line for the ground truth

I suppose you have done that already but there is not much I can say until I have seen the error message. Also you said you are new to matlab but do you have some experience in other programming languages ?

Testing the "otsu.m" file is also a good idea to make sure it works as expected. It takes a normalized grayscale image as an input (gray values from 0 to 1), so you can not just give it the color image obtained with imread. (just give it either the R, G or B channel). I have not seen the output but it should be 2 numbers + 1 array : k_optim is the threshold value and eta_optim is the corresponding value of the separability measure (a statistical measure used to find the optimal threshold). sigmaList is an array with other statistical data useful for my project. You can then use  k_optim to create the segmentation by thresholding the input image.

**Comment by vattyboy** [comment]
Sorry, i was replying through my email, I know the C, C++, and Python Programming, but I'm trying learn Image Processing Using MATLAB for my Final Year Project next Semester.
So, i entered 002, and Otsu as you said,, and here are the errors.

![outputs](https://user-images.githubusercontent.com/30211988/38729751-98247dac-3f31-11e8-850b-945f6907b484.JPG)

**Comment by RomanFenioux** [comment]
OK perfect.

So the `regionprops` function is from the Image Processing toolbox. It is used along with `bwconncomp` in the preprocessing stage to identify the black frame around the image and in the postprocessing stage, to identify and discard small regions (or "islands") using connected component analysis. 

To deactivate the blackframe removal and the CCA, set `compute_blackframe` and `compute_CCA` to `false` at the begining of the script OneImageSegt (in the preprocessing and postprocessing options). The program should run and give you a result.

**Comment by RomanFenioux** [comment]
To test bwconncomp and regionprops, tell me if the following code throws any error:
I=[1 0 0; 0 0 0 ; 0 1 1];
CC = bwconncomp(I)
 stats = regionprops('table',CC,'boundingbox')

**Comment by vattyboy** [comment]
So, i tried the same thing on my R2017a version and i didnt get the regionrpops error,But instead a path error. This is without changing compute _blackframe and compute_CCA to False


![2018-04-13](https://user-images.githubusercontent.com/30211988/38736555-090d1d22-3f4a-11e8-9511-db2fa1f6ac98.png)

**Comment by vattyboy** [comment]
I ran your above code on my R2017a version. I got no error.

**Comment by RomanFenioux** [comment]
I think I get it. 
Replace the relative path '../data/norestriction/'  by an absolute path to the same directory. Something like '/home/[your]/[absolute]/[path]/data/norestriction'

**Comment by vattyboy** [comment]
I replaced it in line 28, still th same errors.

![2018-04-13 2](https://user-images.githubusercontent.com/30211988/38743221-2b4e2edc-3f5c-11e8-8be8-ab22e09c5137.png)

**Comment by RomanFenioux** [comment]
I managed to reproduce your errors on a windows OS and I get the same error.
The problem is that the windows path formatting uses \ as a separator, but in `getData.m` I concatenate the path value with /training and /truth, using a / separator because I developped the program on a Unix system.

So the short answer is: you can't use absolute path, so revert the value of path to  'path = ../data/norestriction' and you have to launch the program from /Skin_Lesion/code/ . Meaning that this should be your current folder (refer to the left panel) when you run the code.

**Comment by vattyboy** [comment]
That is exactly how i open the file, through its containg folder. So there's nothing that can be done?

**Comment by vattyboy** [comment]
I got the output,  as you said, I had to change to \ separator. Got the lesion output. Thank You!

**Comment by vattyboy** [comment]
Hello there again, so i ran SegtEvalution file, and it gave an error saying 

Undefined function or variable 'clear_border'.
Error in segtEvaluation (line 100)
    Isegt=postProc(I_seuil,compute_filling, compute_CCA, clear_border);

 So i just deleted the clear_border , and i got the output. Please tell me if there is something wrong with that,. Also, did Clear_border solve a specific purpose?

**Comment by RomanFenioux** [comment]
You're welcome ! I will add some indications for future users.

clear_border is not really useful. It is a boolean used to say wether you accept regions that touches the limits of the image. When set to true, such regions are automatically discarded. But there are some cases where to lesion actually reaches the borders of the image, so I don't use this criterion anymore.
You should set it to false rather than delete it because I don't remember if the default behavior is true or false.

Le 14 avr. 2018 à 17:28, vattyboy <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hello there again, so i ran SegtEvalution file, and it gave an error saying

Undefined function or variable 'clear_border'.
Error in segtEvaluation (line 100)
Isegt=postProc(I_seuil,compute_filling, compute_CCA, clear_border);

So i just deleted the clear_border , and i got the output. Please tell me if there is something wrong with that,. Also, did Clear_border solve a specific purpose?
